# Generated by Django 4.2 on 2024-02-01 16:52

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
            ],
            options={
                'verbose_name': 'Cursus',
                'verbose_name_plural': 'Cursus',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
            },
        ),
        migrations.CreateModel(
            name='SchoolSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
            ],
            options={
                'verbose_name': 'Système Scolaire',
                'verbose_name_plural': 'Systèmes Scolaire',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.cursus')),
            ],
            options={
                'verbose_name': "Niveau D'étude",
                'verbose_name_plural': "Niveaux D'étude",
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.cursus')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.level', verbose_name="Niveaux d'étude")),
                ('school_system', models.ManyToManyField(to='study.schoolsystem', verbose_name='Systèmes scolaire')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.serie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du cours')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.formation')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'unique_together': {('name', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_file', models.FileField(null=True, upload_to='exam_file/', validators=[core.utils.validate_latex_file], verbose_name="Fiche d'examen")),
                ('exam_year', models.IntegerField(verbose_name="Année de l'examen")),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': "Fiche d'examen",
                'verbose_name_plural': "Fiches d'examen",
                'unique_together': {('course', 'exam_year')},
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du chapitre')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouter le')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'unique_together': {('name', 'course')},
            },
        ),
    ]
